"""Capture a real Electricity Maps trace for later identical replay."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import time
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

try:  # direct `python scripts/capture_carbon.py`
    from _common import required_environment, resolve_path  # type: ignore
except ImportError:  # package `python -m scripts.capture_carbon`
    from scripts._common import required_environment, resolve_path  # type: ignore

from carbon_scheduler.carbon_client import ElectricityMapsClient  # noqa: E402
from carbon_scheduler.settings import ConfigurationError, load_experiment_config  # noqa: E402


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Capture authenticated Electricity Maps latest/forecast snapshots. "
            "The output contains provider responses represented by the client; "
            "no values are generated by this script."
        )
    )
    parser.add_argument("--config", required=True, help="completed experiment YAML")
    parser.add_argument("--output", help="JSON trace destination; defaults to carbon.replay_trace_path")
    parser.add_argument("--cycles", type=int, default=1, help="number of snapshots to capture")
    parser.add_argument("--interval-seconds", type=float, default=0.0)
    parser.add_argument("--timeout-seconds", type=float, default=15.0)
    return parser


def capture_trace(
    *,
    config_path: str | Path,
    output_path: str | Path,
    cycles: int,
    interval_seconds: float,
    timeout_seconds: float,
) -> Path:
    if cycles < 1:
        raise ValueError("cycles must be at least one")
    if interval_seconds < 0:
        raise ValueError("interval_seconds must not be negative")
    config = load_experiment_config(config_path)
    token = required_environment("ELECTRICITY_MAPS_API_KEY")
    client = ElectricityMapsClient(
        api_token=token,
        cache_directory=resolve_path(
            os.environ.get("CARBON_CACHE_DIRECTORY", "").strip()
            or config.carbon.cache_directory
        ),
        cache_max_age=timedelta(seconds=config.carbon.cache_max_age_seconds),
        api_base_url=config.carbon.api_base_url,
        provider=config.carbon.provider,
        forecast_horizon_hours=config.carbon.forecast_horizon_hours,
        timeout_seconds=timeout_seconds,
    )
    regions = {
        config.azure.primary_region: config.carbon.primary_provider_region,
        config.azure.secondary_region: config.carbon.secondary_provider_region,
    }
    snapshots: list[dict[str, Any]] = []
    for index in range(cycles):
        snapshot = client.fetch_snapshot(regions, decision_time=datetime.now(UTC))
        snapshots.append(snapshot.model_dump(mode="json"))
        print(
            f"captured cycle {index + 1}/{cycles}: snapshot={snapshot.snapshot_id} "
            f"sources={','.join(sorted({item.source.value for item in snapshot.regions.values()}))}"
        )
        if index + 1 < cycles and interval_seconds:
            time.sleep(interval_seconds)

    destination = resolve_path(output_path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "format_version": 1,
        "captured_at": datetime.now(UTC).isoformat(),
        "configuration_path": str(resolve_path(config_path)),
        "snapshots": snapshots,
    }
    # load_replay_trace accepts a list of snapshots, while this envelope gives
    # operators useful provenance. The runner understands both forms.
    destination.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    digest = hashlib.sha256(destination.read_bytes()).hexdigest()
    print(f"wrote carbon trace: {destination} sha256={digest}")
    return destination


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        config = load_experiment_config(args.config)
        output = args.output or config.carbon.replay_trace_path
        if not output:
            raise ConfigurationError(
                "--output is required when carbon.replay_trace_path is empty"
            )
        capture_trace(
            config_path=args.config,
            output_path=output,
            cycles=args.cycles,
            interval_seconds=args.interval_seconds,
            timeout_seconds=args.timeout_seconds,
        )
    except Exception as error:
        print(f"capture failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
